[package]
name = "twitch-helix"
version = "0.1.0"
authors = ["Filipe Rodrigues <filipejacintorodrigues1@gmail.com>"]
edition = "2018"

[dependencies]

# Web
url = "2.1"

# Error
thiserror = "1.0"

# Serde
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
